public class HBT_HorasExtrasConstantes {
    public static final String RECARGO_NOCTURNO_FESTIVO = '001066';
    public  static final String REGARGO_NOCTURNO = '001060';
    public static final String HORA_EXTRA_DIURNA = '001061';
    public static final String HORA_EXTRA_NOCTURNA = '001062';
    public static final String DOMINICAL_FESTIVO = '100000';
    public static final String HORA_EXTRA_DIURNA_FESTIVA = '001063';
    public static final String HORA_EXTRA_NOCTURNA_FESTIVA = '001064';
}